name: python application test with github action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.14.2
        uses: actions/setup-python@v6
        with:
          python-version: 3.14.2
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: Test with pytest
        run: |
          make test
      - name: format code
        run: |
          make format
      - name: Build container image
        run: |
          make build
